modLoader = "javafml" #mandatory
loaderVersion = "[31,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "GNU GENERAL PUBLIC LICENSE"
[[mods]] #mandatory
modId = "rsinfinitybooster" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "RSInfinityBooster" #mandatory
description = '''

'''
[[dependencies.rsinfinitybooster]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[31,)" #mandatory
ordering = "NONE"
side = "BOTH"
[[dependencies.rsinfinitybooster]]
modId = "minecraft"
mandatory = true
versionRange = "[1.15.2]"
ordering = "NONE"
side = "BOTH"
[[dependencies.rsinfinitybooster]]
modId = "refinedstorage"
versionRange = "[1.8.8,)"
mandatory = true
ordering = "AFTER"
side = "BOTH"
